name: cd

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: haithemsboui/sma-assistant-frontend:latest
    
    - name: SSH to VPS and update container
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          docker pull haithemsboui/sma-assistant-frontend:latest
          docker stop sma-assistant-frontend || true
          docker rm sma-assistant-frontend || true
          docker run -d \
            --name sma-assistant-frontend \
            -p 4200:4200 \
            -e API_URL=sma-assistant-backend
            haithemsboui/sma-assistant-frontend:latest

          for i in {1..10}; do
            status=$(docker inspect -f '{{.State.Running}}' sma-assistant-frontend)
            if [ "$status" = "true" ]; then
            echo "sma-assistant-frontend Container started successfully."
            exit 0
            else
            echo "Waiting for sma-assistant-frontend container to start... ($i/10)"
            sleep 3
            fi
          done

          echo "sma-assistant-frontend Container failed to start!"
          docker logs sma-assistant-frontend
          exit 1
